version: "3"

services:
  app:
    build:
      context: .
      args:
        - DATABASE_URL=${DATABASE_URL}
    command: npm run dev
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - AUTH_DOMAINS=${AUTH_DOMAINS}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - LINK_EDITING=${LINK_EDITING}
      - HOST=0.0.0.0
      - PORT=${PORT}

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    # ports:
    #   - "3306:3306"
    environment:
      MYSQL_DATABASE: fastforward
      MYSQL_ROOT_PASSWORD: root
